name: Build image with Docker

description: |
  This action build an OCI image with Docker.

inputs:
  context:
    description: context flag
    default: "."
    required: false
  dockerfile:
    description: dockerfile flag
    default: Dockerfile
    required: false
  push:
    description: push image to registry
    required: false
    default: "false"
  tags:
    description: list of image tags
    required: true
  labels:
    description: list of image labels
    required: false

runs:
  using: composite
  steps:
    - run: |
        set -o errexit

        # Build docker kargs
        [ -n "${{ inputs.dockerfile }}" ] && kargs="$kargs --file ${{ inputs.dockerfile }} "

        TAGS=(${{ inputs.tags }})
        for tag in "${TAGS[@]}"; do
          kargs="$kargs --tag $tag "
        done

        # Replace `spaces` by `-`
        LABELS=($(echo "${{ inputs.labels }}" | tr ' ' '-'))
        for label in "${LABELS[@]}"; do
          kargs="$kargs --label \"$label\" "
        done

        # Execute docker build command
        echo "Docker flags: $kargs"
        docker build $kargs ${{ inputs.context }}
      shell: bash

    - if: ${{ inputs.push }} == 'true'
      run: |
        set -o errexit

        TAGS=(${{ inputs.tags }})
        for tag in "${TAGS[@]}"; do
          docker image push $tag
        done
      shell: bash
